export const ORBIT_CACHE_TAGS = {
  eventTypes: "orbit:event-types",
  groups: "orbit:groups",
  lives: "orbit:lives",
  livesDetail: "orbit:lives:detail",
  members: "orbit:members",
  membersDetail: "orbit:members:detail",
  membersList: "orbit:members:list",
  people: "orbit:people",
  releases: "orbit:releases",
  releasesDetail: "orbit:releases:detail",
  releasesList: "orbit:releases:list",
  songOptions: "orbit:song-options",
  songs: "orbit:songs",
  songsDetail: "orbit:songs:detail",
  songsList: "orbit:songs:list",
  spots: "orbit:spots",
  spotsDetail: "orbit:spots:detail",
  top: "orbit:top",
  venues: "orbit:venues",
} as const;
