export const ORBIT_CACHE_TAGS = {
  eventTypes: "orbit:event-types",
  groups: "orbit:groups",
  members: "orbit:members",
  membersDetail: "orbit:members:detail",
  membersList: "orbit:members:list",
  people: "orbit:people",
  releases: "orbit:releases",
  releasesDetail: "orbit:releases:detail",
  releasesList: "orbit:releases:list",
  songOptions: "orbit:song-options",
  songs: "orbit:songs",
  songsDetail: "orbit:songs:detail",
  songsList: "orbit:songs:list",
  top: "orbit:top",
} as const;
